from utils.error import CustomException


class DatabaseError(CustomException):
    """Exception raised for errors in the Database class."""

    pass
